version: '3.8'

services:
  chatbot:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: npm run test:watch
    environment:
      - NODE_ENV=development 